### ISSUE TITLE
Bot doesn't work on multi screen systems 

### ISSUE THREAD

**Issue by ftywaste** [MarkusJx/autobet#8]
**Describe the bug**
the bot doesnt work on a system with multiple screeens. it is clicking to the left of the horse cards. ive already tried using the configurator, but it didnt help.

**To Reproduce**
1. have a system with 2 screens
2. start the bot.

**Log files**

[out.log](https://github.com/MarkusJx/autobet/files/5118177/out.log)

**Comment by MarkusJx** [comment]
Hi,
so I've actually used this program with a multi-screen screen setup (using one myself, too, woah) and it works just fine. So in order to solve this issue, I would need some more information:

- It seems like your screens are not the same resolution, judging by the combined resolution of 3200 by 1088 pixels. The 1088 seems off, but the 3200 pixels are definitely not a multiple of 1920. So what resolutions are your monitors?
- On which monitor have you tried running the game on?
- Will the program actually press any other buttons (e.g. start the race when you manually select a horse)?
- What happens when you disable one screen in the (windows) settings and run it again?
- Are you running the game in windowed, borderless or fullscreen mode?
- At 14:25:10 in the log, you start the game, but the program reports the game's x-coordinate was 33696 pixels (which makes no sense), with a height and width of 0. Was the game minimized at this point?
- At 15:12:40, the betting is again started, the game's x and y-coordinates were 0, the resolution was 1920x1080. I'm assuming at this point you were running the game on your primary screen in fullscreen mode and max resolution. Is that correct?
- Are your screens running on their max resolution?
- Are you running any software for your mouse? These can actually cause severe problems.

Okay, once you've answered these questions, we can hopefully solve this issue.

Have a good one.

**Comment by ftywaste** [comment]
one is 1920x1080 and one is 1280x1024 

on the 1080 one.

no. it keeps clicking left to the horses

i tried unpugging one of my monitors and then it worked.

i tried running in fullscreen and in borderless mode

do i need to start the bot before the game? if yes, i didnt know that.

i tried fullscreen. so the game was minimized when i tabbed out to press the start button.

yes.

yes,

i use a logitech mouse with the logitech gaming software.


thanks for the quick response :)

**Comment by MarkusJx** [comment]
Interesting. Maybe.
So I am currently not able to start the game (probably rockstar's servers down), but I do know in fact someone with a similar configuration. And I also know that the program works just fine on their end.

And since some mouse software can cause problems with programs moving your mouse (someone told me this, he was using roccat software), like this one, try uninstalling/disabling the logitech software and see if the problem is solved.

If this does not help, I would ask you to use the ``--debug:full`` command-line option and send me some of the images saved on your desktop in a zip file. Just so I am able to see, if the game size detection and scaling works.
